version: '3'
services:
  website:
    build:
      context: ./wepsite
      dockerfile: wepsite.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
      - server
  database:
    build:
      context: ./database
      dockerfile: database.dockerfile
    volumes:
      - dbv:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: computerScience
      MYSQL_DATABASE: uni_db
    ports:
      - "3307:3306"
  server:
    build: 
      context: ./wepsite
      dockerfile: server.dockerfile
    ports: 
      - "3000:3000" 
    depends_on:
      - database  
volumes:
  dbv:
